routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false ]);


Route::prefix('backend/')->name('backend.')->group(function (){
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    //Routes for Department
    Route::resource('department','Backend\DepartmentController');

    //Routes for Employee
    Route::resource('employee','Backend\EmployeeController');

});

app/Http/Controllers/Backend/DepartmentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Department\CreateValidation;
use App\Http\Requests\Department\EditValidation;
use App\Model\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DepartmentController extends Controller
{
    //listing of departments
    public function index()
    {
        $data['title']="Listing Departments";
        $data['departments']=Department::all();
        return view('backend.department.index',compact('data'));
    }

    //display create form
    public function create()
    {
        $data['title']="Create Department";
        return view('backend/department/create',compact('data'));
    }

    //storing department data
    public function store(CreateValidation $request)
    {
        $request->request->add(['created_by' => Auth::user()->id]);
        Department::create($request->all());
        $request->session()->flash('success_message','Department Created Successfully');
        return redirect()->route('backend.department.index');
    }

    //view detail of a particular department
    public function show($id)
    {
        $data['department']=Department::find($id);
        $data['title']="View Detail of Department";
        return view('backend.department.show',compact('data'));
    }

    //show edit form
    public function edit($id)
    {
        $data['department']=Department::find($id);
        $data['title']="Edit Department Detail";
        return view('backend.department.edit',compact('data'));
    }

    //update the department data
    public function update(EditValidation $request, $id)
    {
        dd($request);
        if (!$row =  Department::find($id)){
            $request->session()->flash('error_message', 'Invalid Request !');
            return back();
        }
//        if($row->getOriginal('title') != $request->title) {
//            $this->validate($request, [
//                'title' => 'required|unique:departments.title',
//            ]);
//        }
        $request->request->add(['updated_by' => Auth::user()->id]);
        $row->update($request->all());
        $request->session()->flash('success_message', 'Department Information Updated Successfully');
        return redirect()->route('backend.department.index');
    }

    //delete department data
    public function destroy(Request $request,$id)
    {
        if (!$row =  Department::find($id)){
            $request->session()->flash('message', 'Invalid Request !');
            return back();
        }
        $row->delete();
        $request->session()->flash('success_message','Department Delete Successfully');
        return redirect()->route('backend.department.index');
    }
}

app/Http/Controllers/Backend/EmployeeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Employee\CreateValidation;
use App\Http\Requests\Employee\EditValidation;
use App\Model\Department;
use App\Model\Employee;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class EmployeeController extends Controller
{
    //listing employees
    public function index()
    {
        $data['title']="Listing Employees";
        $data['employees']=Employee::all();
        return view('backend.employee.index',compact('data'));
    }

    //show create form
    public function create()
    {
        $data['title']="Create Employee";
        $data['department_id']=Department::where('status','1')->pluck('title','id');
        $data['department_id']->prepend('Select Department','');
        return view('backend.employee.create',compact('data'));
    }

    //storing of employee information
    public function store(CreateValidation $request)
    {
        if($request->file('employee_photo')){
            $photo = $request->file('employee_photo');
            $photo_name = rand(6785, 9814) . '_' . $photo->getClientOriginalName();
            $photo->move('images/employee', $photo_name);
            $request->request->add(['photo'=>$photo_name]);
        }
        $request->request->add(['created_by' => Auth::user()->id]);
        Employee::create($request->all());
        $request->session()->flash('success_message','Department Created Successfully');
        return redirect()->route('backend.employee.index');
    }

    //details of selected employee
    public function show($id)
    {
        $data['employee']=Employee::find($id);
        $data['title']="View Detail of Employee";
        return view('backend.employee.show',compact('data'));
    }

    //show edit form
    public function edit($id)
    {
        $data['employee']=Employee::find($id);
        $data['title']="Edit Employee Detail";
        $data['department_id']=Department::where('status','1')->pluck('title','id');
        $data['department_id']->prepend($data['employee']->department->title , $data['employee']->department->id );
        $data['department_id']->prepend('Select Department','');
        return view('backend.employee.edit',compact('data'));
    }

    //update employee information
    public function update(EditValidation $request,$id)
    {
//        dd($id);
        if (!$row =  Employee::find($id)){
            $request->session()->flash('error_message', 'Invalid Request !');
            return back();
        }

        if($row->getOriginal('email') != $request->email) {
            $this->validate($request, [
                'email' => 'required|unique:employees|email'
            ]);
        }

        //upload new photo and delete old photo
        if($request->file('employee_photo')){
            $photo = $request->file('employee_photo');
            $photo_name = rand(6785, 9814) . '_' . $photo->getClientOriginalName();
            $photo->move('images/employee', $photo_name);
            $request->request->add(['photo'=>$photo_name]);

            //remove existing photo
            if (file_exists('images/employee.' . $row->photo))
                unlink('images/employee.' . $row->photo);
        }

        $request->request->add(['updated_by' => Auth::user()->id]);
        $row->update($request->all());
        $request->session()->flash('success_message', 'Employee Information Updated Successfully');
        return redirect()->route('backend.employee.index');
    }

    //delete employee information
    public function destroy(Request $request,$id)
    {
        if (!$row =  Employee::find($id)){
            $request->session()->flash('message', 'Invalid Request !');
            return back();
        }
        //Remove old photo from folder
        if($row->photo && file_exists('images/employee/'.$row->photo)){
            unlink('images/employee/'.$row->photo);
        }
        $row->delete();
        $request->session()->flash('success_message','Employee Delete Successfully');
        return redirect()->route('backend.employee.index');
    }
}

resources/views/backend/includes/flash_message.blade.php
@if(session()->has('success_message'))
    <section class="content-header fmessage">
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alert!</h4>
            {!! session()->get('success_message') !!}
        </div>
    </section>
@endif
@if(session()->has('error_message'))
    <section class="content-header fmessage">
        <div class="alert alert-warning alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> Alert!</h4>
            {!! session()->get('error_message') !!}
        </div>
    </section>
@endif

resources/views/backend/includes/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

resources/views/backend/includes/form_field_validation.blade.php
@if($errors->has($fieldname))
    <p class="text-red">{!! $errors->first($fieldname) !!}</p>
@endif

resources/views/backend/includes/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>@if(isset($data['title'])) {{ $data['title'] }} @endif </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('backend/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('backend/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('backend/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('backend/dist/css/AdminLTE.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }} ">

    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('backend/dist/css/skins/_all-skins.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

resources/views/backend/includes/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="../../index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Act360</b>ERMS</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Act360</b>ERMS</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <p>
                                {{ Auth::user()->name }}
                            </p>
                        </li>

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-right">

                                <a class="btn btn-default btn-flat" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/backend/includes/js.blade.php
<!-- jQuery 3 -->
<script src="{{ asset('backend/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('backend/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- SlimScroll -->
<script src="{{ asset('backend/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('backend/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/dist/js/adminlte.min.js') }}"></script>
{{--Ckeditor--}}
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('backend/dist/js/demo.js') }}"></script>
<script>
    $(document).ready(function () {
        $('.sidebar-menu').tree()
    })
</script>

@yield('js')

resources/views/backend/includes/menu.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <i class="fa fa-user"></i>
            </div>
            <div class="pull-left info">
                <p>
                    {{ Auth::user()->name }}</p>
            </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li >
                <a href="{{ route('backend.dashboard') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>

            {{--Department--}}
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-building"></i>
                    <span>Department Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('backend.department.create') }}"><i class="fa fa-circle-o"></i> Create</a></li>
                    <li><a href="{{ route('backend.department.index') }}"><i class="fa fa-circle-o"></i> List</a></li>
                </ul>
            </li>

            {{--Employee--}}
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span>Employee Management</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('backend.employee.create') }}"><i class="fa fa-circle-o"></i> Create</a></li>
                    <li><a href="{{ route('backend.employee.index') }}"><i class="fa fa-circle-o"></i> List</a></li>
                </ul>
            </li>

        </ul>

    </section>
    <!-- /.sidebar -->
</aside>